Dev
adku1173/acoupipe pull request #42
Opened 2024-05-21 07:40 UTC by adku1173

*  adds support to randomize the signal length
* changes transfer function normalization (relative to the reference position)

2024-05-24 09:25 UTC, artpelling requested changes

2024-05-24 09:25 UTC, artpelling commented on .github/workflows/build_and_test.yml
> -        os: [ubuntu-latest, macos-latest, windows-latest]
why did we change?

2024-05-31 09:19 UTC, adku1173 commented on .github/workflows/build_and_test.yml
> -        os: [ubuntu-latest, macos-latest, windows-latest]
https://github.com/acoular/acoular/issues/209 -> I am following the Acoular CI here. For macos-latest, the hardware choice is non-deterministic and the pipeline fails sporadically. To make the CI consistent, we simply use macos-13 here.

2024-05-31 12:48 UTC, artpelling approved these changes

2024-05-31 12:48 UTC, merged